from gamekit.systems.actions import Action
QUIT = Action()
PAUSE = Action()
FULL_SCREEN = Action()
MOVE_FORWARD = Action()
MOVE_BACKWARD = Action()
MOVE_LEFT = Action()
MOVE_RIGHT = Action()
TURN_LEFT = Action()
TURN_RIGHT = Action()
FIRE = Action()
WEAPON_GUN = Action()
WEAPON_SHOTGUN = Action()
WEAPON_ASSAULT = Action()
